# Generated by Django 4.2.11 on 2025-03-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0002_auto_20221212_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooltip',
            fields=[
            ],
            options={
                'verbose_name': 'Tooltip',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
