# Generated by Django 3.1.14 on 2022-12-12 11:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenduiitem',
            name='config',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
