# Generated by Django 4.2.11 on 2024-03-22 11:45

from django.db import migrations
import djangocms_frontend.contrib.link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0002_auto_20221212_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
            ],
            options={
                'verbose_name': 'Counter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(djangocms_frontend.contrib.link.models.GetLinkMixin, 'djangocms_frontend.frontenduiitem'),
        ),
    ]
