# Generated by Django 3.1.14 on 2022-12-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTML',
            fields=[
            ],
            options={
                'verbose_name': 'Raw HTML',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
