# Generated by Django 3.2.16 on 2023-03-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_frontend', '0002_auto_20221212_1107'),
        ('custom_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTMLWithID',
            fields=[
            ],
            options={
                'verbose_name': 'Raw HTML With ID',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
