# Generated by Django 3.2.16 on 2023-05-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_frontend', '0002_auto_20221212_1107'),
        ('custom_plugins', '0002_rawhtmlwithid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatedContent',
            fields=[
            ],
            options={
                'verbose_name': 'Gated Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
