# Generated by Django 3.2.16 on 2023-07-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_frontend', '0002_auto_20221212_1107'),
        ('custom_plugins', '0004_gatedtrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
            ],
            options={
                'verbose_name': 'Custom plugin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
