# Generated by Django 3.1.14 on 2022-12-06 13:09

from django.db import migrations
import djangocms_frontend.contrib.link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
            ],
            options={
                'verbose_name': 'Promo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(djangocms_frontend.contrib.link.models.GetLinkMixin, 'djangocms_frontend.frontenduiitem'),
        ),
    ]
